block      =  { "{" ~ block_body? ~ "}" }
block_body = _{ (field | decl)* }

field = { "[" ~ typeID ~ "]" ~ "=" ~ block }

Id     = @{ ('a'..'z')+ }
typeID = @{ Id ~ ("." ~ typeID)? }

decl = { "let" ~ Id ~ "=" ~ (string) ~ ";" }

string = ${ "\"" ~ inner ~ "\"" }
inner  = @{ char* }
char   =  {
    !("\"" | "\\") ~ ANY
  | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
  | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }